Repository Kushal997-das/SkillShow, pull requests merged in 2024-10, with the labels that each got.

#10 Password Strength Checker #4
  Beginner Level 📁/Password Strength Checker/question.md
  Beginner Level 📁/Password Strength Checker/solution.py
  Beginner Level 📁/data.json
Labels: good first issue, Approved✅, hacktoberfest-accepted, hacktoberfest2024

#13 Add new user to data.json and implement Grid Maximum Path Sum solution
  Beginner Level 📁/Grid Maximum Path Sum/Solution.cpp
  Beginner Level 📁/Grid Maximum Path Sum/question.md
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#15 Added Roman to Integer question
  Beginner Level 📁/Roman to Integer/question.md
  Beginner Level 📁/Roman to Integer/solution.java
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#22 Add "Find the Shortest Path in a Weighted Graph" question
  Beginner Level 📁/Shortest Path/question.md
  Beginner Level 📁/Shortest Path/solution.py
  Beginner Level 📁/data.json
  README.md
Labels: good first issue, Approved✅, hacktoberfest-accepted, hacktoberfest2024

#39 Banner added for SkillShow Project ✨
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2024

#76 MIn and Max
  Beginner Level 📁/data.json
  Beginner Level 📁/max_min/answer.js
  Beginner Level 📁/max_min/question.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2024

#78 Adding a Question about the Fibonacci series
  Beginner Level 📁/nth fibonacci series/answer.js
  Beginner Level 📁/nth fibonacci series/question.md
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#109 car with max capacity
  Beginner Level 📁/car with max capacity/problem.md
  Beginner Level 📁/car with max capacity/solution.js
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#46 Update solution.py
  Beginner Level 📁/Password Strength Checker/solution.py
Labels: Approved✅

#50 Spiral matrix solution
  Beginner Level 📁/Spiral matrix/question.md
  Beginner Level 📁/Spiral matrix/solution.js
  Beginner Level 📁/data.json
Labels: hacktoberfest-accepted, hacktoberfest2024

#82 Maximal Score After Applying K Operations problem and solution
  Beginner Level 📁/Maximal Score/question.md
  Beginner Level 📁/Maximal Score/solution.cpp
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#88 Program to Count Set Bits in a Number
  Beginner Level 📁/Count Set Bit in Number/CountBit.java
  Beginner Level 📁/Count Set Bit in Number/question.md
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#86 Added question and solution of "Number of days in a month"
  Beginner Level 📁/Number of days in a month/question.md
  Beginner Level 📁/Number of days in a month/solution.java
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#38 Added Solution for Triangle Quest
  Beginner Level 📁/Triangle Quest/main.py
  Beginner Level 📁/Triangle Quest/question.md
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#89 Feat/longest sub seq that sums to target
  Beginner Level 📁/Length_of_the_Longest_Subsequence_That_Sums_to_Target/qustion.md
  Beginner Level 📁/Length_of_the_Longest_Subsequence_That_Sums_to_Target/solution.cpp
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#121 Implement two classes: `Car` and `Boat` to handle different types of vehicles.
  Beginner Level 📁/Car and Boat/question.md
  Beginner Level 📁/Car and Boat/solution.py
  Beginner Level 📁/data.json
Labels: Approved✅, hacktoberfest-accepted, hacktoberfest2024

#85 Added my project
  Beginner Level 📁/Calculator/question.md
  Beginner Level 📁/Calculator/solution.ts
  Beginner Level 📁/data.json
Labels: hacktoberfest2024, Hold

#115 Create question.md and solution.cpp
  Beginner Level 📁/Maximum Swap/question.md
  Beginner Level 📁/Maximum Swap/solution.cpp
  Beginner Level 📁/data.json
Labels: hacktoberfest2024, Hold
